name: 2) Build and deploy to Heroku

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & push Docker image
        with:
          image: react-easy-ssr-staticfiles
          tag: ${GITHUB_REF##*/}
          registry: registry.heroku.com/react-easy-ssr-staticfiles/web
          dockerfile: Dockerfile
          username: thomas.aumaitre@gmail.com
          password: ${{ secrets.HEROKU_API_KEY }}