name: 2) Build and deploy to Heroku

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "react-easy-ssr-staticfiles"
          heroku_email: "thomas.aumaitre@gmail.com"